### ISSUE TITLE
Touch events

### ISSUE THREAD

**Issue by dmjio** [haskell-miso/miso#121]
Will probably need to implement them as a subscription. `touchstart`, `touchend`, etc.

**Comment by ptigwe** [comment]
've looked into this a bit. As one might expect, creating the listeners is quite trivial. The main issue comes when you try to decode the event. Unlike other events (like mouse and keyboard), with touch events, the data resides within objects nested within the event object. I attempted modifying the `objectToJSON` function so as to extract some of this info, which is where I'm currently stuck at. I've tried but not so sure as to how to modify the `jsvalToValue` function so that it is capable of parsing nested objects. I keep getting `TypeError: Cannot read property 't' of undefined`. Not really sure how to proceed.

```javascript
function objectToJSON (at, obj) {
  for (var i in at) obj = obj[at[i]];
  console.log(obj);
  var newObj = objToJSON(obj, 2);
  console.log(newObj);
  return (newObj);
}

function objToJSON (obj, rec) {
  var newObj = {}
  for (var i in obj) {
    if (typeof obj[i] == "string" || typeof obj[i] == "number" || typeof obj[i] == "boolean")
      newObj[i] = obj[i];
    else if (typeof obj[i] == "object" && rec != 0 && i == "changedTouches") {
      newObj[i] = objToJSON(obj[i], rec - 1);
    }
  }
  return (newObj);
}```

**Comment by ptigwe** [comment]
Thanks to @dmjio, the following code resolves this issue and enables reading the first touch event. In the situation where only a single touch is required, the following code should suffice.

```haskell
touchDecoder :: Decoder Touch
touchDecoder = Decoder {..}
  where
    decodeAt = ["touches", "0"]
    decoder = withObject "touch" $ \o -> 
          Touch <$> o .: "clientX" <*> o .: "clientY" 

onTouchMove :: (Touch -> action) -> Attribute action
onTouchMove = on "touchmove" touchDecoder
```

**Comment by dmjio** [comment]
awesome, 👌
