### ISSUE TITLE
SVG example source?

### ISSUE THREAD

**Issue by srid** [haskell-miso/miso#243]
The svg example is [linked in README](https://github.com/haskell-miso/miso/blob/master/README.md#svg) - but there is no link to its source. I would be interested!

**Comment by dmjio** [comment]
@srid, Ah, yea I was meaning to come back to this. Wanted to simplify this example by default, since at present it shows more functionality than just SVG (shows keys and mouse too). I think we should keep the mouse movement along with the SVG, since it's cool. But we should probably remove everything else.

Here is the source. I can add it in soon. **Note**: This doesn't include click handlers that change the color (which might be cool to include as well).

https://gist.github.com/dmjio/ad79a85d61601571bf2c1101c606dd72

**Comment by srid** [comment]
@dmjio - thanks, I've modified your example to work on latest Miso: https://github.com/srid/miso-viso/blob/a535d5905245b17d1896b8def5d3b0e6bbdc8937/Main.hs

**Comment by dmjio** [comment]
@srid, awesome thanks. I'll try to merge this upstream.

**Comment by dmjio** [comment]
https://github.com/haskell-miso/miso/commit/a701010f6ccb967a32e80f969026c387e58d1586
