### ISSUE TITLE
Don't drop events by default

### ISSUE THREAD

**Issue by cocreature** [haskell-miso/miso#279]
Currently `miso` will just silently drop events once the bounded chan is full. This is bound to confuse users and imho the wrong default. My understanding is that the justification for doing this is that it can improve the performance in some cases, specifically games where mouse events can be dropped without doing too much harm. However, even in games there will probably other events which should not be dropped so I’d argue that even in that case the current behavior is undesired.

That leaves us with two questions:
1. How do we change the code to not drop events? We definitely need to change `writeEvent` so it doesn’t discard events which basically just means replacing `tryWriteChan` with `writeChan`. This means that we will block if the chan is full. Afaict this cannot lead to a deadlock since we have a separate thread which always reads events so this is the solution that I would prefer. The alternative would be to use an unbounded channel. However, channels that get arbitrarily long are usually not desired so I don’t think that’s a good solution.
2. If dropping mouse events actually improves the performance, we should provide a way for users to get these performance improvements. However, I am not sure if dropping events is really required for this. Users could just write `update` functions that ignore some events which means we don’t diff which would help if diffing and redrawing is the bottleneck here. It would be great if @dmjio could provide the benchmarks to test if this gives similar gains. An alternative would be to write custom subs for mouse events that drop events if there are two many within a given time frame (or based on some other criterion).

**Comment by dmjio** [comment]
Can confirm that events are in fact getting dropped in the mario example (to be expected), when an arrow key is held down. Can also confirm that when `writeChan` is traded for `tryWriteChan`, that the memory growth is linear (peaks at ~1MB), and gameplay becomes extremely sluggish.

<img width="308" alt="screen shot 2017-08-29 at 9 00 47 pm" src="https://user-images.githubusercontent.com/875324/29854922-8b1ff280-8cfd-11e7-9029-669851d49363.png">

> My understanding is that the justification for doing this is that it can improve the performance in some cases, specifically games where mouse events can be dropped without doing too much harm.

The justification for now is to avoid space leaks.

> However, even in games there will probably other events which should not be dropped so I’d argue that even in that case the current behavior is undesired

I agree.

> How do we change the code to not drop events? We definitely need to change writeEvent so it doesn’t discard events which basically just means replacing tryWriteChan with writeChan. This means that we will block if the chan is full. Afaict this cannot lead to a deadlock since we have a separate thread which always reads events so this is the solution that I would prefer. The alternative would be to use an unbounded channel. However, channels that get arbitrarily long are usually not desired so I don’t think that’s a good solution.

Switching from `tryWriteChan` to `writeChan` has the same effect as using an unbounded channel, instead of congestion at the read end of the queue, it just moves congestion to the write end of the queue. So it isn't clear what is the best course of action yet, but what is clear is that this will affect games. Flatris for example, drops events, but it doesn't seem to adversely affect gameplay. Another thing to consider, serious game developers will use canvas instead of the DOM. Therefore, they will have higher throughput since they can bypass both model and view diffing (so will be less likely drop events). But in the case of DOM-heavy games (like Flatris), dropping is a concern (albeit in contrived cases -- holding down an arrow key to rotate a piece will cause drops, but in this case the drops are all related to piece rotation).

> An alternative would be to write custom subs for mouse events that drop events if there are two many within a given time frame (or based on some other criterion).

Interesting, hadn't thought of this.

**Comment by dmjio** [comment]
Solved in https://github.com/haskell-miso/miso/commit/3177aec07eef230632907f31b5738757431884df thanks to @cocreature. `BoundedChan` has been removed as well.
